### ISSUE TITLE
Multiple Files

### ISSUE THREAD

**Issue by alleekirk** [ekapope/WorldWeatherOnline#1]
When I run the script through a loop from different Zip codes on different days the program overwrites the original file when same zips are processed. For instance, I have the same 5 zips on different days, the .csv file is overwritten each time. 

How do I store all processed zips, with different dates, into one .csv file without overwrite?

**Comment by ekapope** [comment]
Hi @alleekirk ,

I am not sure if I understood your question correctly. By default, the function will automatically save csv (_export_csv = True_) by using location input.

If you want to customize your file name, you can simply change _export_csv = False_ and use pandas to_csv method to manually save dataframe output for each location.
