### ISSUE TITLE
urllib has no attribute "requests"

### ISSUE THREAD

**Issue by ConsCount** [ekapope/WorldWeatherOnline#14]
When I run the sample code, it told me that "module urllib has no attribute requests" I found the solution that you can change the "import urllib" to "import urllib.requests" at line 13 in file "__init__.py"

**Comment by gpspelle** [comment]
Great!

**Comment by EvanGoldConn** [comment]
Yep. Had this same issue. Tried creating a pull request to throw in in there, so maybe it'll change. Cheers.

**Comment by ekapope** [comment]
Thanks @EvanGoldConn 👍
