### ISSUE TITLE
Missing update to new premium URL

### ISSUE THREAD

**Issue by mdalvi** [ekapope/WorldWeatherOnline#2]
http://api.worldweatheronline.com/premium/v1/weather.ashx

**Comment by ekapope** [comment]
Hi @mdalvi,

Your url is for 'Local Weather API'. However, this package currently covers only 'Past/Historical Weather API'.

Let me know if I understood correctly since you did not give any context.

**Comment by mdalvi** [comment]
You are right. Thanks for the information.
