### ISSUE TITLE
period of 3-hour

### ISSUE THREAD

**Issue by Hololensmoon** [ekapope/WorldWeatherOnline#3]
Hi,
Thanks for your information. The problem I faced with this is that I need the historical data of each 15-minutes for a specific period of time. But it seems that this website just provides information regarding the 3-hours period of time.  Even if I change the frequency to 1, it again retrieves the data for the 3-hour period of time.

**Comment by ekapope** [comment]
Hi,
https://www.worldweatheronline.com/developer/premium-api-explorer.aspx
The minimum interval is 1 hr. I have checked the script, setting frequency = 1 gave me 1 hour interval. This works fine for me.
