### ISSUE TITLE
Error while Forecast with 2 days in the end of month

### ISSUE THREAD

**Issue by gasiali** [ekapope/WorldWeatherOnline#4]
In the endo of month when trying to get forecasted data based on 2 days  more precisely ,(30 Nov 2019 & 01 Dec 2019) it give reindex problem as trying to loop back whole November data.Can someone helps me in this.

**Comment by ekapope** [comment]
I have tested it and it worked fine for me. Please let me know if u still need help.

`frequency=1
start_date = '30-NOV-2019'
end_date = '01-DEC-2019'
api_key = 'XXX'
location_list = ['hamburg']

df = retrieve_hist_data(api_key,
                                location_list,
                                start_date,
                                end_date,
                                frequency,
                                location_label = False,
                                export_csv = True,
                                store_df = True)`
