### ISSUE TITLE
Last Month comes two times

### ISSUE THREAD

**Issue by FSH-SI** [ekapope/WorldWeatherOnline#5]
First of all: amazing work! You saved me a lot of time for trying out on my own. Thank you very much!

While using the package a behavior occured I could not understand. I collected historical weather data for complete year 2018 from 01-JAN-2018 to 31-DEC-2018. For some reason the december was retrieved two times. no problem at all - I just deleted one december afterwards but maybe you have an idea how to repair this.

best regards,
fabian 

![BUG](https://user-images.githubusercontent.com/51951752/74356644-f81d0d80-4dbe-11ea-8dac-9e79caec4aaf.png)

**Comment by ekapope** [comment]
Hi @FSH-SI ,

Thank you for your feedback, I believed this issue has been fixed #6 .

Cheers
Ekapope
